0. Basic Imports

from pprint import pprint
import pandas as pd
import zrd_login
import datetime
import pdb



kite = zrd_login.kite
pdb.set_trace()





1. convert string to datetime python
	from dateutil.parser import parse
	datetime = parse('2018-06-29 22:21:41')
	datetime = parse(date, dayfirst=True)

2. For loop on pandas
	for index, row in df.iterrows():

3. pandas set index
	df.set_index('month')

4. pandas rename columns
	df.rename(columns={"A": "a", "B": "b", "C": "c"}, errors="raise")

5. pandas select only few columns
	dfx = df[['open', 'high']]

6. replace text in pandas
dfx['date'].str.replace('.', ':')


7. xlwings

import xlwings as xw
wb = xw.Book('results.xlsx')
sht = wb.sheets['Sheet1']
watch_list = sht2.range('A1').expand().value
print(watch_list)

8. 
    dbfile = open('examplePickle', 'ab') 
    pickle.dump(db, dbfile) 

    dbfile = open('examplePickle', 'rb')
    db = pickle.load(dbfile) 

9. slice pnadas string in columns
nifty_dates = df["date"].str.slice(0, 10).unique()


10. python separate numbers from string
int(''.join(filter(str.isdigit, cell_no)))


11. pandas shift column down
	df.['date'].shift(1)

12. pandas put 0 ,1 in place of true false
	df["somecolumn"] = df["somecolumn"].astype(int)


13. datetime combination for example
	dd-mm-yyyy h.mm

14. pandas drop columns
	df = df.drop(['confluence_candle_param'], axis = 1)

15. read data from relatine path
	pd.read_csv("Data Files/nifty.csv")


16. check for instance 
	if isinstance(trailing_indicator, dict):
		pass

17. STEP VALUE
	https://www1.nseindia.com/content/fo/sos_scheme.xls

18. drop columns
	df.drop(['B', 'C'], axis=1)

19. pandas arrange rows by list
	df.reindex(watchlist)
	

20. mis order
	# mis market
	kite.place_order(variety = kite.VARIETY_REGULAR , exchange = kite.EXCHANGE_NSE , tradingsymbol = name[4:] , transaction_type = kite.TRANSACTION_TYPE_SELL , quantity = 1 , product = kite.PRODUCT_MIS , order_type = kite.ORDER_TYPE_MARKET , price=None, validity=None, disclosed_quantity=None, trigger_price=None, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)

	# mis slm
	buy_order_id = kite.place_order(variety=kite.VARIETY_REGULAR, exchange=kite.EXCHANGE_NSE, tradingsymbol=name, transaction_type=kite.TRANSACTION_TYPE_BUY, quantity=qty, product=kite.PRODUCT_MIS, order_type=kite.ORDER_TYPE_SLM, price=None, validity=None, disclosed_quantity=None, trigger_price=buy_trigger_price, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)

21. amo orders
	kite.place_order(variety = kite.VARIETY_AMO, exchange= kite.EXCHANGE_NSE, tradingsymbol = name, transaction_type = kite.TRANSACTION_TYPE_SELL, quantity = lot_size, product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_MARKET, price = None, validity = None, disclosed_quantity = None, trigger_price = None, squareoff = None, stoploss = None, trailing_stoploss = None, tag = None)

	amo market order
	kite.place_order(variety = kite.VARIETY_AMO, exchange = kite.EXCHANGE_NSE, tradingsymbol = 'ACC', transaction_type = kite.TRANSACTION_TYPE_BUY, quantity = 36, product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_MARKET, price=None, validity=None, disclosed_quantity=None, trigger_price=None, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)

	amo slm order
	kite.place_order(variety = kite.VARIETY_AMO, exchange = kite.EXCHANGE_NSE, tradingsymbol = 'CIPLA', transaction_type = kite.TRANSACTION_TYPE_BUY, quantity = 360, product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_SLM, price=None, validity=None, disclosed_quantity=None, trigger_price=800, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)

	amo limit
	kite.place_order(variety = kite.VARIETY_AMO, exchange = kite.EXCHANGE_NSE, tradingsymbol = name , transaction_type = kite.TRANSACTION_TYPE_BUY, quantity = status[name]['qty'] , product = kite.PRODUCT_MIS, order_type = kite.ORDER_TYPE_LIMIT, price=candle['low'], validity=None, disclosed_quantity=None, trigger_price=800, squareoff=None, stoploss=None, trailing_stoploss=None, tag=None)


22. remove timezone form timestamp
	df['date'] =  df['date'].dt.tz_localize(None)

23.
	from colorama import init
	from colorama import Fore, Back, Style

	init()
	print(Fore.RED + 'some red text')
	Fore: BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE, RESET.

24.
	from dateutil.parser import parse
	datetime = parse('2018-06-29 22:21:41')

25. remove timezone
	df.iloc[-1]['date'].replace(tzinfo=None)


26.
	detailed traceback

import traceback
import sys


try:
	print(1/0)
except Exception as e:
	print(e)
	exc_info = sys.exc_info()
	traceback.print_exception(*exc_info)


27. find forst occurance
	candles[candles['rsi'] > 60].first_valid_index()

nifty names storage

nifty100LowVolatility30list : 	watchlist = ['ACC', 'ASIANPAINT', 'BAJAJ-AUTO', 'BOSCHLTD', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'COLPAL', 'DABUR', 'DRREDDY', 'HCLTECH', 'HDFCBANK', 'HEROMOTOCO', 'HINDUNILVR', 'HDFC', 'ITC', 'IOC', 'INFY', 'KOTAKBANK', 'LT', 'MARICO', 'NTPC', 'NESTLEIND', 'PIDILITIND', 'POWERGRID', 'RELIANCE', 'TCS', 'TECHM', 'ULTRACEMCO', 'WIPRO']
nifty200Momentum30_list : 		watchlist = ['ASIANPAINT', 'AUROPHARMA', 'BALKRISIND', 'BERGEPAINT', 'BHARTIARTL', 'BIOCON', 'BRITANNIA', 'CADILAHC', 'CIPLA', 'COLPAL', 'DABUR', 'DIVISLAB', 'DRREDDY', 'ESCORTS', 'GMRINFRA', 'HINDUNILVR', 'IGL', 'NAUKRI', 'JUBLFOOD', 'LUPIN', 'MGL', 'MUTHOOTFIN', 'NESTLEIND', 'PIDILITIND', 'RELIANCE', 'SRF', 'SHREECEM', 'TATACONSUM', 'TORNTPHARM', 'TORNTPOWER']
nifty50list : 					watchlist = ['ADANIPORTS', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BPCL', 'BHARTIARTL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'GAIL', 'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'HDFC', 'ICICIBANK', 'ITC', 'IOC', 'INDUSINDBK', 'INFY', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NTPC', 'NESTLEIND', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE', 'SHREECEM', 'SBIN', 'SUNPHARMA', 'TCS', 'TATAMOTORS', 'TATASTEEL', 'TECHM', 'TITAN', 'UPL', 'ULTRACEMCO', 'WIPRO']
niftymidcap50list : 			watchlist = ['ADANIENT', 'AMARAJABAT', 'APOLLOHOSP', 'APOLLOTYRE', 'ASHOKLEY', 'BALKRISIND', 'BANKINDIA', 'BATAINDIA', 'BEL', 'BHARATFORG', 'BHEL', 'CANBK', 'CASTROLIND', 'CHOLAFIN', 'COFORGE', 'CUMMINSIND', 'ESCORTS', 'EXIDEIND', 'FEDERALBNK', 'GMRINFRA', 'GLENMARK', 'GODREJPROP', 'IDFCFIRSTB', 'IBULHSGFIN', 'JINDALSTEL', 'JUBLFOOD', 'L&TFH', 'LICHSGFIN', 'MRF', 'MGL', 'M&MFIN', 'MANAPPURAM', 'MFSL', 'MINDTREE', 'NATIONALUM', 'PAGEIND', 'RBLBANK', 'RECLTD', 'SRF', 'SRTRANSFIN', 'SAIL', 'SUNTV', 'TVSMOTOR', 'TATAPOWER', 'RAMCOCEM', 'TORNTPOWER', 'UNIONBANK', 'IDEA', 'VOLTAS', 'ZEEL']
niftysmallcap50list : 			watchlist = ['AVANTIFEED', 'BAJAJELEC', 'BDL', 'BIRLACORPN', 'CANFINHOME', 'CEATLTD', 'CENTURYTEX', 'CHAMBLFERT', 'COCHINSHIP', 'CYIENT', 'DCBBANK', 'DCMSHRIRAM', 'DEEPAKNTR', 'DBL', 'DIXON', 'GMMPFAUDLR', 'GODFRYPHLP', 'GRANULES', 'GRAPHITE', 'IDFC', 'IRCON', 'INDIAMART', 'INDIANB', 'KAJARIACER', 'KEC', 'LAURUSLABS', 'LINDEINDIA', 'MOIL', 'MIDHANI', 'MCX', 'NBCC', 'PNBHOUSING', 'PVR', 'PERSISTENT', 'PGHL', 'RITES', 'RADICO', 'RVNL', 'RALLIS', 'SPICEJET', 'STLTECH', 'STAR', 'SPARC', 'SUNTECK', 'TV18BRDCST', 'TATAELXSI', 'UJJIVANSFB', 'VIPIND', 'VAKRANGEE', 'WOCKPHARMA']
nifty_Alpha_Index : 			watchlist = ['ABBOTINDIA', 'ADANIENT', 'ADANIGREEN', 'ATGL', 'AJANTPHARM', 'APLLTD', 'AMBER', 'ASTRAZEN', 'DMART', 'BALKRISIND', 'BAYERCROP', 'BERGEPAINT', 'BSOFT', 'CDSL', 'COFORGE', 'COROMANDEL', 'DEEPAKNTR', 'DIVISLAB', 'DIXON', 'LALPATHLAB', 'DRREDDY', 'EIDPARRY', 'ESCORTS', 'GMMPFAUDLR', 'GRANULES', 'GUJGASLTD', 'HCLTECH', 'ISEC', 'INDIAMART', 'NAUKRI', 'IPCALAB', 'JBCHEPHARM', 'JINDALSTEL', 'JUBLFOOD', 'LAURUSLABS', 'METROPOLIS', 'MCX', 'MUTHOOTFIN', 'NAVINFLUOR', 'NESTLEIND', 'PIIND', 'RALLIS', 'RELAXO', 'RELIANCE', 'SRF', 'TATACONSUM', 'TORNTPHARM', 'TRENT', 'VBL', 'IDEA']
nifty_alpha_lowvol30list : 		watchlist = ['AMBUJACEM', 'ASIANPAINT', 'BERGEPAINT', 'BIOCON', 'BRITANNIA', 'CADILAHC', 'CIPLA', 'COLPAL', 'DABUR', 'DIVISLAB', 'DRREDDY', 'HCLTECH', 'HAVELLS', 'HINDUNILVR', 'IGL', 'INFY', 'LUPIN', 'MRF', 'MARICO', 'NESTLEIND', 'PIDILITIND', 'POWERGRID', 'RELIANCE', 'SRF', 'SHREECEM', 'TCS', 'TORNTPHARM', 'TORNTPOWER', 'VOLTAS', 'WIPRO']
nifty_High_Beta50_Index : 		watchlist = ['ADANIPORTS', 'APOLLOTYRE', 'ASHOKLEY', 'AXISBANK', 'BAJFINANCE', 'BAJAJFINSV', 'BANDHANBNK', 'BANKBARODA', 'BHEL', 'BPCL', 'CANFINHOME', 'CANBK', 'CHOLAFIN', 'COFORGE', 'DLF', 'ESCORTS', 'FEDERALBNK', 'GODREJPROP', 'GRASIM', 'HINDALCO', 'HDFC', 'ICICIBANK', 'ICICIPRULI', 'IDFCFIRSTB', 'IBULHSGFIN', 'INDUSINDBK', 'JSWSTEEL', 'JINDALSTEL', 'L&TFH', 'LICHSGFIN', 'M&MFIN', 'MANAPPURAM', 'MARUTI', 'MFSL', 'MOTHERSUMI', 'MUTHOOTFIN', 'NMDC', 'NAM-INDIA', 'PEL', 'PFC', 'RBLBANK', 'RADICO', 'SRTRANSFIN', 'SBIN', 'SAIL', 'TATAMOTORS', 'TATASTEEL', 'UJJIVAN', 'VEDL', 'IDEA']
fno								watchlist = ['BPCL', 'MOTHERSUMI', 'RBLBANK', 'SIEMENS', 'GODREJPROP', 'CANBK', 'MARICO', 'BEL', 'NAVINFLUOR', 'CADILAHC', 'SRF', 'DEEPAKNTR', 'UBL', 'NAUKRI', 'LUPIN', 'PVR', 'COLPAL', 'PNB', 'IOC', 'BHEL', 'PETRONET', 'IDFCFIRSTB', 'GRANULES', 'EICHERMOT', 'M&MFIN', 'VOLTAS', 'IGL', 'HINDPETRO', 'TVSMOTOR', 'TATACHEM', 'BANDHANBNK', 'HAVELLS', 'SUNTV', 'AUBANK', 'L&TFH', 'ADANIENT', 'M&M', 'LTI', 'HDFC', 'MINDTREE', 'INFY', 'RAMCOCEM', 'TATAMOTORS', 'SUNPHARMA', 'TITAN', 'SBILIFE', 'POWERGRID', 'VEDL', 'AARTIIND', 'NTPC', 'IBULHSGFIN', 'LICHSGFIN', 'UPL', 'RECLTD', 'BOSCHLTD', 'APLLTD', 'BRITANNIA', 'COFORGE', 'NAM-INDIA', 'JSWSTEEL', 'NMDC', 'GRASIM', 'HDFCAMC', 'HDFCLIFE', 'JINDALSTEL', 'PFC', 'SHREECEM', 'BANKBARODA', 'LTTS', 'AMARAJABAT', 'HCLTECH', 'APOLLOTYRE', 'MCDOWELL-N', 'BALKRISIND', 'ICICIGI', 'ALKEM', 'CUB', 'IRCTC', 'MPHASIS', 'ULTRACEMCO', 'AXISBANK', 'ASIANPAINT', 'TORNTPOWER', 'BHARATFORG', 'HINDALCO', 'ESCORTS', 'TATACONSUM', 'ZEEL', 'ASHOKLEY', 'DLF', 'GUJGASLTD', 'ICICIPRULI', 'LT', 'TORNTPHARM', 'CHOLAFIN', 'JUBLFOOD', 'ITC', 'INDUSTOWER', 'SRTRANSFIN', 'GMRINFRA', 'HEROMOTOCO', 'LALPATHLAB', 'EXIDEIND', 'BAJFINANCE', 'DABUR', 'GODREJCP', 'NATIONALUM', 'PEL', 'BIOCON', 'TCS', 'GAIL', 'GLENMARK', 'ACC', 'APOLLOHOSP', 'CIPLA', 'BAJAJ-AUTO', 'PIIND', 'BHARTIARTL', 'NESTLEIND', 'INDIGO', 'MRF', 'SBIN', 'COALINDIA', 'AUROPHARMA', 'DIVISLAB', 'BAJAJFINSV', 'RELIANCE', 'IDEA', 'TATAPOWER', 'WIPRO', 'ADANIPORTS', 'BERGEPAINT', 'TATASTEEL', 'FEDERALBNK', 'MFSL', 'KOTAKBANK', 'MGL', 'HINDUNILVR', 'TECHM', 'DRREDDY', 'SAIL', 'MARUTI', 'ICICIBANK', 'BATAINDIA', 'MUTHOOTFIN', 'HDFCBANK', 'ONGC', 'INDUSINDBK', 'PIDILITIND', 'AMBUJACEM', 'PAGEIND', 'TRENT', 'CONCOR', 'PFIZER', 'MANAPPURAM', 'CUMMINSIND']
nifty 500                       watchlist = ['3MINDIA', 'ABB', 'POWERINDIA', 'ACC', 'AIAENG', 'APLAPOLLO', 'AUBANK', 'AARTIDRUGS', 'AARTIIND', 'AAVAS', 'ABBOTINDIA', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ATGL', 'ADANITRANS', 'ABCAPITAL', 'ABFRL', 'ADVENZYMES', 'AEGISCHEM', 'AFFLE', 'AJANTPHARM', 'AKZOINDIA', 'ALEMBICLTD', 'APLLTD', 'ALKEM', 'ALKYLAMINE', 'ALOKINDS', 'AMARAJABAT', 'AMBER', 'AMBUJACEM', 'ANGELBRKG', 'APOLLOHOSP', 'APOLLOTYRE', 'ASAHIINDIA', 'ASHOKLEY', 'ASHOKA', 'ASIANPAINT', 'ASTERDM', 'ASTRAZEN', 'ASTRAL', 'ATUL', 'AUROPHARMA', 'AVANTIFEED', 'DMART', 'AXISBANK', 'BASF', 'BEML', 'BSE', 'BAJAJ-AUTO', 'BAJAJCON', 'BAJAJELEC', 'BAJFINANCE', 'BAJAJFINSV', 'BAJAJHLDNG', 'BALAMINES', 'BALKRISIND', 'BALMLAWRIE', 'BALRAMCHIN', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'MAHABANK', 'BATAINDIA', 'BAYERCROP', 'BERGEPAINT', 'BDL', 'BEL', 'BHARATFORG', 'BHEL', 'BPCL', 'BHARATRAS', 'BHARTIARTL', 'BIOCON', 'BIRLACORPN', 'BSOFT', 'BLISSGVS', 'BLUEDART', 'BLUESTARCO', 'BBTC', 'BOSCHLTD', 'BRIGADE', 'BRITANNIA', 'BURGERKING', 'CCL', 'CESC', 'CRISIL', 'CSBBANK', 'CADILAHC', 'CANFINHOME', 'CANBK', 'CAPLIPOINT', 'CGCL', 'CARBORUNIV', 'CASTROLIND', 'CEATLTD', 'CENTRALBK', 'CDSL', 'CENTURYPLY', 'CENTURYTEX', 'CERA', 'CHALET', 'CHAMBLFERT', 'CHOLAHLDNG', 'CHOLAFIN', 'CIPLA', 'CUB', 'COALINDIA', 'COCHINSHIP', 'COFORGE', 'COLPAL', 'CAMS', 'CONCOR', 'COROMANDEL', 'CREDITACC', 'CROMPTON', 'CUMMINSIND', 'CYIENT', 'DCBBANK', 'DCMSHRIRAM', 'DLF', 'DABUR', 'DALBHARAT', 'DEEPAKNTR', 'DELTACORP', 'DHANI', 'DHANUKA', 'DBL', 'DISHTV', 'DCAL', 'DIVISLAB', 'DIXON', 'LALPATHLAB', 'DRREDDY', 'EIDPARRY', 'EIHOTEL', 'EPL', 'EDELWEISS', 'EICHERMOT', 'ELGIEQUIP', 'EMAMILTD', 'ENDURANCE', 'ENGINERSIN', 'EQUITAS', 'ERIS', 'ESCORTS', 'EXIDEIND', 'FDC', 'FEDERALBNK', 'FINEORG', 'FINCABLES', 'FINPIPE', 'FSL', 'FORTIS', 'FCONSUMER', 'FRETAIL', 'GAIL', 'GEPIL', 'GMMPFAUDLR', 'GMRINFRA', 'GALAXYSURF', 'GRSE', 'GARFIBRES', 'GICRE', 'GILLETTE', 'GLAXO', 'GLENMARK', 'GODFRYPHLP', 'GODREJAGRO', 'GODREJCP', 'GODREJIND', 'GODREJPROP', 'GRANULES', 'GRAPHITE', 'GRASIM', 'GESHIP', 'GREAVESCOT', 'GRINDWELL', 'GUJALKALI', 'GAEL', 'FLUOROCHEM', 'GUJGASLTD', 'GNFC', 'GPPL', 'GSFC', 'GSPL', 'GULFOILLUB', 'HEG', 'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HFCL', 'HAPPSTMNDS', 'HATSUN', 'HAVELLS', 'HEIDELBERG', 'HEMIPROP', 'HEROMOTOCO', 'HSCL', 'HINDALCO', 'HAL', 'HINDCOPPER', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'HONAUT', 'HUDCO', 'HDFC', 'HUHTAMAKI', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'ISEC', 'IDBI', 'IDFCFIRSTB', 'IDFC', 'IFBIND', 'IIFL', 'IIFLWAM', 'IOLCP', 'IRB', 'IRCON', 'ITC', 'ITI', 'INDIACEM', 'IBULHSGFIN', 'IBREALEST', 'INDIAMART', 'INDIANB', 'IEX', 'INDHOTEL', 'IOC', 'IOB', 'IRCTC', 'ICIL', 'INDOCO', 'IGL', 'INDUSTOWER', 'INDUSINDBK', 'INFIBEAM', 'NAUKRI', 'INFY', 'INGERRAND', 'INOXLEISUR', 'INTELLECT', 'INDIGO', 'IPCALAB', 'JBCHEPHARM', 'JKCEMENT', 'JKLAKSHMI', 'JKPAPER', 'JKTYRE', 'JMFINANCIL', 'JSWENERGY', 'JSWSTEEL', 'JTEKTINDIA', 'JAMNAAUTO', 'JINDALSAW', 'JSLHISAR', 'JSL', 'JINDALSTEL', 'JCHAC', 'JUBLFOOD', 'JUSTDIAL', 'JYOTHYLAB', 'KPRMILL', 'KEI', 'KNRCON', 'KPITTECH', 'KRBL', 'KSB', 'KAJARIACER', 'KALPATPOWR', 'KANSAINER', 'KARURVYSYA', 'KSCL', 'KEC', 'KOTAKBANK', 'L&TFH', 'LTTS', 'LICHSGFIN', 'LAOPALA', 'LAXMIMACH', 'LTI', 'LT', 'LAURUSLABS', 'LEMONTREE', 'LINDEINDIA', 'LUPIN', 'LUXIND', 'MASFIN', 'MMTC', 'MOIL', 'MRF', 'MGL', 'MAHSCOOTER', 'MAHSEAMLES', 'M&MFIN', 'M&M', 'MAHINDCIE', 'MHRIL', 'MAHLOG', 'MANAPPURAM', 'MRPL', 'MARICO', 'MARUTI', 'MFSL', 'MAXHEALTH', 'MAZDOCK', 'METROPOLIS', 'MINDTREE', 'MINDACORP', 'MINDAIND', 'MIDHANI', 'MOTHERSUMI', 'MOTILALOFS', 'MPHASIS', 'MCX', 'MUTHOOTFIN', 'NATCOPHARM', 'NBCC', 'NCC', 'NESCO', 'NHPC', 'NLCINDIA', 'NMDC', 'NOCIL', 'NTPC', 'NH', 'NATIONALUM', 'NFL', 'NAVINFLUOR', 'NESTLEIND', 'NETWORK18', 'NILKAMAL', 'NAM-INDIA', 'OBEROIRLTY', 'ONGC', 'OIL', 'OFSS', 'ORIENTELEC', 'ORIENTREF', 'PIIND', 'PNBHOUSING', 'PNCINFRA', 'PVR', 'PAGEIND', 'PERSISTENT', 'PETRONET', 'PFIZER', 'PHILIPCARB', 'PHOENIXLTD', 'PIDILITIND', 'PEL', 'POLYMED', 'POLYCAB', 'POLYPLEX', 'PFC', 'POWERGRID', 'PRESTIGE', 'PRINCEPIPE', 'PRSMJOHNSN', 'PGHL', 'PGHH', 'PNB', 'QUESS', 'RBLBANK', 'RECLTD', 'RITES', 'RADICO', 'RVNL', 'RAIN', 'RAJESHEXPO', 'RALLIS', 'RCF', 'RATNAMANI', 'RAYMOND', 'REDINGTON', 'RELAXO', 'RELIANCE', 'RESPONIND', 'ROSSARI', 'ROUTE', 'SBICARD', 'SBILIFE', 'SIS', 'SJVN', 'SKFINDIA', 'SRF', 'SANOFI', 'SCHAEFFLER', 'SCHNEIDER', 'SEQUENT', 'SHARDACROP', 'SFL', 'SHILPAMED', 'SCI', 'SHOPERSTOP', 'SHREECEM', 'SHRIRAMCIT', 'SRTRANSFIN', 'SIEMENS', 'SOBHA', 'SOLARINDS', 'SOLARA', 'SONATSOFTW', 'SPANDANA', 'SPICEJET', 'STARCEMENT', 'SBIN', 'SAIL', 'SWSOLAR', 'STLTECH', 'STAR', 'SUDARSCHEM', 'SUMICHEM', 'SPARC', 'SUNPHARMA', 'SUNTV', 'SUNCLAYLTD', 'SUNDARMFIN', 'SUNDRMFAST', 'SUNTECK', 'SUPRAJIT', 'SUPREMEIND', 'SUPPETRO', 'SUVENPHAR', 'SUZLON', 'SWANENERGY', 'SYMPHONY', 'SYNGENE', 'TCIEXP', 'TCNSBRANDS', 'TTKPRESTIG', 'TV18BRDCST', 'TVSMOTOR', 'TANLA', 'TASTYBITE', 'TATACHEM', 'TATACOFFEE', 'TATACOMM', 'TCS', 'TATACONSUM', 'TATAELXSI', 'TATAINVEST', 'TATAMTRDVR', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TEAMLEASE', 'TECHM', 'NIACL', 'RAMCOCEM', 'THERMAX', 'THYROCARE', 'TIMKEN', 'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TRENT', 'TRIDENT', 'TRITURBINE', 'TIINDIA', 'UCOBANK', 'UFLEX', 'UPL', 'UTIAMC', 'UJJIVAN', 'UJJIVANSFB', 'ULTRACEMCO', 'UNIONBANK', 'UBL', 'MCDOWELL-N', 'VGUARD', 'VMART', 'VIPIND', 'VSTIND', 'VAIBHAVGBL', 'VAKRANGEE', 'VALIANTORG', 'VTL', 'VARROC', 'VBL', 'VEDL', 'VENKEYS', 'VINATIORGA', 'IDEA', 'VOLTAS', 'WABCOINDIA', 'WELCORP', 'WELSPUNIND', 'WESTLIFE', 'WHIRLPOOL', 'WIPRO', 'WOCKPHARMA', 'YESBANK', 'ZEEL', 'ZENSARTECH', 'ZYDUSWELL', 'ECLERX']
both_in_nse_bse                 watchlist = ['20MICRONS', '21STCENMGM', '3MINDIA', '3PLAND', '5PAISA', '63MOONS', 'AARTIDRUGS', 'AARTIIND', 'AARTISURF', 'AARVEEDEN', 'AAVAS', 'ABB', 'ABBOTINDIA', 'ABCAPITAL', 'ABFRL', 'ABSLAMC', 'ABSLBANETF', 'ABSLNN50ET', 'ACC', 'ACCELYA', 'ACE', 'ACRYSIL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'ADFFOODS', 'ADORWELD', 'ADSL', 'ADVANIHOTR', 'ADVENZYMES', 'AFFLE', 'AGARIND', 'AHLEAST', 'AHLUCONT', 'AIAENG', 'AJANTPHARM', 'AJMERA', 'AJRINFRA', 'AKSHOPTFBR', 'AKZOINDIA', 'ALANKIT', 'ALEMBICLTD', 'ALICON', 'ALKALI', 'ALKEM', 'ALKYLAMINE', 'ALLCARGO', 'ALLSEC', 'ALMONDZ', 'ALPA', 'ALPHAGEO', 'AMARAJABAT', 'AMBER', 'AMBICAAGAR', 'AMBIKCO', 'AMBUJACEM', 'AMDIND', 'AMIORG', 'AMJLAND', 'AMRUTANJAN', 'ANANDRATHI', 'ANANTRAJ', 'ANDHRACEMT', 'ANDHRAPAP', 'ANDHRSUGAR', 'ANDREWYU', 'ANGELONE', 'ANIKINDS', 'ANMOL', 'ANUP', 'ANURAS', 'APARINDS', 'APCL', 'APCOTEXIND', 'APEX', 'APLAPOLLO', 'APLLTD', 'APOLLO', 'APOLLOHOSP', 'APOLLOTYRE', 'APTECHT', 'APTUS', 'ARCHIDPLY', 'ARCHIES', 'ARENTERP', 'ARIES', 'ARMANFIN', 'AROGRANITE', 'ARROWGREEN', 'ARSHIYA', 'ARSSINFRA', 'ARTEMISMED', 'ARVIND', 'ARVINDFASN', 'ASAHIINDIA', 'ASAHISONG', 'ASALCBR', 'ASHAPURMIN', 'ASHIANA', 'ASHIMASYN', 'ASHOKA', 'ASHOKLEY', 'ASIANENE', 'ASIANHOTNR', 'ASIANPAINT', 'ASIANTILES', 'ASTEC', 'ASTERDM', 'ASTRAL', 'ASTRAMICRO', 'ASTRAZEN', 'ASTRON', 'ATFL', 'ATUL', 'ATULAUTO', 'AUBANK', 'AURIONPRO', 'AUROPHARMA', 'AURUM', 'AUSOMENT', 'AUTOAXLES', 'AUTOIND', 'AVADHSUGAR', 'AVTNPL', 'AWHCL', 'AXISBANK', 'AXISCADES', 'AXISCETF', 'AXISGOLD', 'AXISTECETF', 'AYMSYNTEX', 'BAJAJ-AUTO', 'BAJAJCON', 'BAJAJELEC', 'BAJAJFINSV', 'BAJAJHCARE', 'BAJAJHIND', 'BAJAJHLDNG', 'BAJFINANCE', 'BALAJITELE', 'BALAMINES', 'BALKRISHNA', 'BALKRISIND', 'BALMLAWRIE', 'BALPHARMA', 'BALRAMCHIN', 'BANARBEADS', 'BANARISUG', 'BANCOINDIA', 'BANDHANBNK', 'BANG', 'BANKBARODA', 'BANKBEES', 'BANKINDIA', 'BANSWRAS', 'BARBEQUE', 'BASF', 'BASML', 'BATAINDIA', 'BAYERCROP', 'BBETF0432', 'BBL', 'BBOX', 'BBTC', 'BCP', 'BDL', 'BEARDSELL', 'BECTORFOOD', 'BEDMUTHA', 'BEL', 'BEML', 'BEPL', 'BERGEPAINT', 'BESTAGRO', 'BFINVEST', 'BFUTILITIE', 'BGRENERGY', 'BHAGCHEM', 'BHAGYAPROP', 'BHARATFORG', 'BHARATGEAR', 'BHARATRAS', 'BHARATWIRE', 'BHARTIARTL', 'BHEL', 'BIGBLOC', 'BIL', 'BINDALAGRO', 'BIOCON', 'BIOFILCHEM', 'BIRLACABLE', 'BIRLACORPN', 'BIRLAMONEY', 'BLBLIMITED', 'BLISSGVS', 'BLKASHYAP', 'BLUEDART', 'BLUESTARCO', 'BODALCHEM', 'BOMDYEING', 'BOROLTD', 'BORORENEW', 'BOSCHLTD', 'BPCL', 'BRIGADE', 'BRITANNIA', 'BRNL', 'BROOKS', 'BSL', 'BSLGOLDETF', 'BSLSENETFG', 'BSOFT', 'BURGERKING', 'BURNPUR', 'CADILAHC', 'CAMLINFINE', 'CAMS', 'CANBK', 'CANFINHOME', 'CAPACITE', 'CARBORUNIV', 'CAREERP', 'CARERATING', 'CARTRADE', 'CASTROLIND', 'CCHHL', 'CCL', 'CEATLTD', 'CEBBCO', 'CELEBRITY', 'CENTENKA', 'CENTEXT', 'CENTRALBK', 'CENTRUM', 'CENTUM', 'CENTURYPLY', 'CENTURYTEX', 'CERA', 'CEREBRAINT', 'CESC', 'CGCL', 'CHALET', 'CHAMBLFERT', 'CHEMBOND', 'CHEMCON', 'CHEMPLASTS', 'CHENNPETRO', 'CHOLAFIN', 'CHOLAHLDNG', 'CINELINE', 'CIPLA', 'CLEAN', 'CLNINDIA', 'COALINDIA', 'COASTCORP', 'COCHINSHIP', 'COFFEEDAY', 'COFORGE', 'COLPAL', 'COMPUSOFT', 'CONCOR', 'CONFIPET', 'CONTROLPR', 'CORALFINAC', 'CORDSCABLE', 'COROMANDEL', 'COSMOFILMS', 'COUNCODOS', 'CPSEETF', 'CRAFTSMAN', 'CREDITACC', 'CRISIL', 'CROMPTON', 'CSBBANK', 'CTE', 'CUB', 'CUBEXTUB', 'CUMMINSIND', 'CUPID', 'CYBERMEDIA', 'CYBERTECH', 'CYIENT', 'DAAWAT', 'DABUR', 'DALBHARAT', 'DALMIASUG', 'DATAMATICS', 'DATAPATTNS', 'DBCORP', 'DBL', 'DBSTOCKBRO', 'DCAL', 'DCBBANK', 'DCMNVL', 'DCMSHRIRAM', 'DECCANCE', 'DEEPAKFERT', 'DEEPENR', 'DELPHIFX', 'DELTACORP', 'DELTAMAGNT', 'DEN', 'DEVYANI', 'DHAMPURSUG', 'DHANBANK', 'DHANI', 'DHANUKA', 'DHARAMSI', 'DHARSUGAR', 'DHRUV', 'DHUNINV', 'DIAMONDYD', 'DICIND', 'DIGISPICE', 'DIVISLAB', 'DIXON', 'DLF', 'DLINKINDIA', 'DMART', 'DODLA', 'DOLATALGO', 'DOLLAR', 'DREDGECORP', 'DRREDDY', 'DSPNEWETF', 'DSSL', 'DVL', 'DWARKESH', 'DYNPRO', 'EASTSILK', 'EBBETF0423', 'EBBETF0425', 'EBBETF0430', 'EBBETF0431', 'ECLERX', 'EDELWEISS', 'EICHERMOT', 'EIDPARRY', 'EIHAHOTELS', 'EIHOTEL', 'EIMCOELECO', 'EKC', 'ELECON', 'ELECTCAST', 'ELECTHERM', 'ELGIEQUIP', 'EMAMILTD', 'EMAMIPAP', 'EMAMIREAL', 'EMKAY', 'EMMBI', 'ENDURANCE', 'ENERGYDEV', 'ENGINERSIN', 'ENIL', 'EPL', 'EQUIPPP', 'EQUITAS', 'EQUITASBNK', 'ERIS', 'EROSMEDIA', 'ESABINDIA', 'ESCORTS', 'ESSARSHPNG', 'ESTER', 'EVEREADY', 'EVERESTIND', 'EXCELINDUS', 'EXIDEIND', 'EXPLEOSOL', 'EXXARO', 'FACT', 'FAIRCHEMOR', 'FCL', 'FCONSUMER', 'FDC', 'FEDERALBNK', 'FEL', 'FELDVR', 'FIEMIND', 'FILATEX', 'FINCABLES', 'FINEORG', 'FINOPB', 'FLEXITUFF', 'FLFL', 'FLUOROCHEM', 'FMGOETZE', 'FMNL', 'FOCUS', 'FOODSIN', 'FORCEMOT', 'FORTIS', 'FOSECOIND', 'FRETAIL', 'FSC', 'FSL', 'GABRIEL', 'GAEL', 'GAIL', 'GAL', 'GALAXYSURF', 'GALLANTT', 'GALLISPAT', 'GANDHITUBE', 'GANECOS', 'GANESHBE', 'GANESHHOUC', 'GARFIBRES', 'GATI', 'GAYAPROJ', 'GDL', 'GEECEE', 'GENCON', 'GENESYS', 'GENUSPAPER', 'GENUSPOWER', 'GEOJITFSL', 'GEPIL', 'GESHIP', 'GET&D', 'GFLLIMITED', 'GHCL', 'GICHSGFIN', 'GICRE', 'GILLANDERS', 'GILLETTE', 'GINNIFILA', 'GIPCL', 'GLAND', 'GLAXO', 'GLENMARK', 'GLOBALVECT', 'GLOBUSSPR', 'GLS', 'GMBREW', 'GMDCLTD', 'GMRINFRA', 'GNA', 'GNFC', 'GOACARBON', 'GOCLCORP', 'GOCOLORS', 'GODFRYPHLP', 'GODREJAGRO', 'GODREJCP', 'GODREJIND', 'GODREJPROP', 'GOKEX', 'GOKUL', 'GOKULAGRO', 'GOLDBEES', 'GOLDIAM', 'GOLDSHARE', 'GOODLUCK', 'GOODYEAR', 'GPIL', 'GPPL', 'GPTINFRA', 'GRANULES', 'GRAPHITE', 'GRASIM', 'GRAUWEIL', 'GRAVITA', 'GREAVESCOT', 'GREENPANEL', 'GREENPLY', 'GRINDWELL', 'GRINFRA', 'GRPLTD', 'GRSE', 'GSCLCEMENT', 'GSFC', 'GSPL', 'GTL', 'GTNTEX', 'GTPL', 'GUFICBIO', 'GUJALKALI', 'GUJAPOLLO', 'GULFOILLUB', 'GULFPETRO', 'HAL', 'HAPPSTMNDS', 'HARRMALAYA', 'HATHWAY', 'HATSUN', 'HAVELLS', 'HBANKETF', 'HBLPOWER', 'HCC', 'HCG', 'HCL-INSYS', 'HCLTECH', 'HDFC', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HDFCMFGETF', 'HDFCNIFETF', 'HEG', 'HEIDELBERG', 'HEMIPROP', 'HERANBA', 'HERCULES', 'HERITGFOOD', 'HEROMOTOCO', 'HESTERBIO', 'HEXATRADEX', 'HFCL', 'HGINFRA', 'HGS', 'HIKAL', 'HIL', 'HIMATSEIDE', 'HINDALCO', 'HINDCOMPOS', 'HINDCOPPER', 'HINDNATGLS', 'HINDOILEXP', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'HIRECT', 'HITECH', 'HITECHCORP', 'HITECHGEAR', 'HLEGLAS', 'HMVL', 'HNDFDS', 'HNGSNGBEES', 'HOMEFIRST', 'HONAUT', 'HONDAPOWER', 'HOVS', 'HPL', 'HSCL', 'HSIL', 'HTMEDIA', 'HUBTOWN', 'HUDCO', 'HUHTAMAKI', 'IBREALEST', 'IBULHSGFIN', 'ICICI500', 'ICICIALPLV', 'ICICIB22', 'ICICIBANK', 'ICICIBANKN', 'ICICIBANKP', 'ICICICONSU', 'ICICIFMCG', 'ICICIGI', 'ICICIGOLD', 'ICICILIQ', 'ICICILOVOL', 'ICICIM150', 'ICICIMCAP', 'ICICINF100', 'ICICINIFTY', 'ICICINV20', 'ICICINXT50', 'ICICIPHARM', 'ICICIPRULI', 'ICICISENSX', 'ICICITECH', 'ICIL', 'ICRA', 'IDBI', 'IDBIGOLD', 'IDEA', 'IDFC', 'IDFCFIRSTB', 'IEX', 'IFBAGRO', 'IFBIND', 'IFCI', 'IFGLEXPOR', 'IGARASHI', 'IGL', 'IGPL', 'IIFL', 'IIFLSEC', 'IIFLWAM', 'IMFA', 'IMPAL', 'INCREDIBLE', 'INDBANK', 'INDHOTEL', 'INDIACEM', 'INDIAGLYCO', 'INDIAMART', 'INDIANB', 'INDIANCARD', 'INDIANHUME', 'INDIGO', 'INDIGOPNTS', 'INDLMETER', 'INDNIPPON', 'INDOCO', 'INDORAMA', 'INDOSTAR', 'INDOTECH', 'INDOTHAI', 'INDRAMEDCO', 'INDSWFTLAB', 'INDSWFTLTD', 'INDTERRAIN', 'INDUSINDBK', 'INDUSTOWER', 'INEOSSTYRO', 'INFIBEAM', 'INFRABEES', 'INFY', 'INGERRAND', 'INOXLEISUR', 'INOXWIND', 'INSECTICID', 'INTELLECT', 'INTENTECH', 'INTLCONV', 'INVENTURE', 'IOB', 'IOC', 'IOLCP', 'IPCALAB', 'IPL', 'IRB', 'IRCON', 'IRCTC', 'IRFC', 'IRIS', 'ISEC', 'ISFT', 'ISGEC', 'ISMTLTD', 'ITC', 'ITDC', 'ITDCEM', 'ITI', 'IVC', 'IVP', 'IVZINGOLD', 'IZMO', 'J&KBANK', 'JAGRAN', 'JAGSNPHARM', 'JAIBALAJI', 'JAICORPLTD', 'JAMNAAUTO', 'JAYAGROGN', 'JAYBARMARU', 'JBCHEPHARM', 'JBMA', 'JCHAC', 'JETFREIGHT', 'JHS', 'JINDALPHOT', 'JINDALPOLY', 'JINDALSAW', 'JINDALSTEL', 'JINDRILL', 'JINDWORLD', 'JISLJALEQS', 'JKCEMENT', 'JKIL', 'JKLAKSHMI', 'JKPAPER', 'JKTYRE', 'JMCPROJECT', 'JMFINANCIL', 'JPASSOCIAT', 'JPINFRATEC', 'JPPOWER', 'JSL', 'JSLHISAR', 'JSWHL', 'JSWISPL', 'JSWSTEEL', 'JTEKTINDIA', 'JTLINFRA', 'JUBLFOOD', 'JUBLINDS', 'JUBLINGREA', 'JUBLPHARMA', 'JUNIORBEES', 'JUSTDIAL', 'JYOTHYLAB', 'KABRAEXTRU', 'KAJARIACER', 'KAKATCEM', 'KALPATPOWR', 'KALYANKJIL', 'KAMATHOTEL', 'KAMDHENU', 'KANANIIND', 'KANORICHEM', 'KANPRPLA', 'KANSAINER', 'KARMAENG', 'KARURVYSYA', 'KAUSHALYA', 'KAYA', 'KBCGLOBAL', 'KCP', 'KCPSUGIND', 'KDDL', 'KEC', 'KEI', 'KELLTONTEC', 'KENNAMET', 'KESORAMIND', 'KHADIM', 'KHAICHEM', 'KHANDSE', 'KICL', 'KILITCH', 'KIMS', 'KINGFA', 'KIOCL', 'KIRIINDUS', 'KIRLFER', 'KIRLOSBROS', 'KIRLOSENG', 'KIRLOSIND', 'KITEX', 'KKCL', 'KMSUGAR', 'KNRCON', 'KOKUYOCMLN', 'KOLTEPATIL', 'KOPRAN', 'KOTAKBANK', 'KOTAKBKETF', 'KOTAKGOLD', 'KOTAKNIFTY', 'KOTAKPSUBK', 'KOTHARIPRO', 'KOVAI', 'KPIGLOBAL', 'KPITTECH', 'KPRMILL', 'KRBL', 'KREBSBIO', 'KRSNAA', 'KSB', 'KSCL', 'KSL', 'KTKBANK', 'KUANTUM', 'L&TFH', 'LALPATHLAB', 'LAMBODHARA', 'LAOPALA', 'LASA', 'LATENTVIEW', 'LAURUSLABS', 'LAXMIMACH', 'LCCINFOTEC', 'LEMONTREE', 'LGBBROSLTD', 'LGBFORGE', 'LIBERTSHOE', 'LICHSGFIN', 'LICNETFN50', 'LICNETFSEN', 'LICNFNHGP', 'LIKHITHA', 'LINC', 'LINDEINDIA', 'LIQUIDBEES', 'LIQUIDETF', 'LODHA', 'LOKESHMACH', 'LPDC', 'LT', 'LTI', 'LTTS', 'LUMAXIND', 'LUMAXTECH', 'LUPIN', 'LUXIND', 'LXCHEM', 'LYKALABS', 'LYPSAGEMS', 'M&M', 'M&MFIN', 'MAANALU', 'MADHAV', 'MADRASFERT', 'MAESGETF', 'MAFANG', 'MAFSETF', 'MAGNUM', 'MAHABANK', 'MAHASTEEL', 'MAHEPC', 'MAHINDCIE', 'MAHKTECH', 'MAHLIFE', 'MAHLOG', 'MAHSCOOTER', 'MAHSEAMLES', 'MAITHANALL', 'MALUPAPER', 'MAN50ETF', 'MANAKSIA', 'MANALIPETC', 'MANAPPURAM', 'MANGALAM', 'MANGCHEFER', 'MANGLMCEM', 'MANGTIMBER', 'MANINDS', 'MANINFRA', 'MANORG', 'MAPMYINDIA', 'MARALOVER', 'MARATHON', 'MARICO', 'MARKSANS', 'MARUTI', 'MASFIN', 'MASPTOP50', 'MASTEK', 'MATRIMONY', 'MAWANASUG', 'MAXHEALTH', 'MAXVIL', 'MAYURUNIQ', 'MAZDOCK', 'MBLINFRA', 'MCLEODRUSS', 'MCX', 'MEDICAMEQ', 'MEDPLUS', 'MENONBE', 'METROBRAND', 'METROPOLIS', 'MFL', 'MFSL', 'MGL', 'MHRIL', 'MIDHANI', 'MINDACORP', 'MINDAIND', 'MINDTECK', 'MINDTREE', 'MIRCELECTR', 'MIRZAINT', 'MMFL', 'MMTC', 'MODISNME', 'MOGSEC', 'MOHITIND', 'MOIL', 'MOL', 'MOLDTKPAC', 'MOM100', 'MOM50', 'MON100', 'MONTECARLO', 'MORARJEE', 'MOREPENLAB', 'MOTHERSUMI', 'MOTILALOFS', 'MPHASIS', 'MPSLTD', 'MRF', 'MRO-TEK', 'MRPL', 'MSPL', 'MTARTECH', 'MTEDUCARE', 'MTNL', 'MUKANDLTD', 'MUKTAARTS', 'MUNJALAU', 'MUNJALSHOW', 'MURUDCERA', 'MUTHOOTFIN', 'NACLIND', 'NAGREEKCAP', 'NAGREEKEXP', 'NAHARCAP', 'NAHARINDUS', 'NAHARPOLY', 'NAM-INDIA', 'NATCOPHARM', 'NATHBIOGEN', 'NATIONALUM', 'NAUKRI', 'NAVINFLUOR', 'NAVKARCORP', 'NAVNETEDUL', 'NBCC', 'NBVENTURES', 'NCC', 'NCLIND', 'NDL', 'NDRAUTO', 'NDTV', 'NECCLTD', 'NECLIFE', 'NELCAST', 'NEOGEN', 'NESCO', 'NESTLEIND', 'NETFNIF100', 'NETWORK18', 'NEULANDLAB', 'NEWGEN', 'NFL', 'NH', 'NHPC', 'NIACL', 'NIBL', 'NIFTYBEES', 'NIITLTD', 'NILKAMAL', 'NIPPOBATRY', 'NIRAJ', 'NITCO', 'NKIND', 'NLCINDIA', 'NMDC', 'NOCIL', 'NOIDATOLL', 'NOVARTIND', 'NRBBEARING', 'NSIL', 'NTPC', 'NUCLEUS', 'NURECA', 'NUVOCO', 'NXTDIGITAL', 'NYKAA', 'OAL', 'OBEROIRLTY', 'OFSS', 'OIL', 'OMAXAUTO', 'OMAXE', 'OMINFRAL', 'ONELIFECAP', 'ONGC', 'ONMOBILE', 'ONWARDTEC', 'OPTIEMUS', 'ORBTEXP', 'ORIENTABRA', 'ORIENTALTL', 'ORIENTBELL', 'ORIENTCEM', 'ORIENTELEC', 'ORIENTHOT', 'ORIENTLTD', 'ORIENTPPR', 'ORISSAMINE', 'OSWALAGRO', 'PAGEIND', 'PAISALO', 'PANACEABIO', 'PANACHE', 'PANAMAPET', 'PARAGMILK', 'PARAS', 'PARSVNATH', 'PASUPTAC', 'PATELENG', 'PATINTLOG', 'PATSPINLTD', 'PAYTM', 'PBAINFRA', 'PCJEWELLER', 'PDMJEPAPER', 'PDSMFL', 'PEARLPOLY', 'PEL', 'PENIND', 'PERSISTENT', 'PETRONET', 'PFC', 'PFIZER', 'PFOCUS', 'PFS', 'PGEL', 'PGHH', 'PGHL', 'PGIL', 'PHILIPCARB', 'PHOENIXLTD', 'PIDILITIND', 'PIIND', 'PILANIINVS', 'PILITA', 'PIONDIST', 'PIONEEREMB', 'PITTIENG', 'PLASTIBLEN', 'PNB', 'PNBGILTS', 'PNBHOUSING', 'PNC', 'PNCINFRA', 'POKARNA', 'POLICYBZR', 'POLYCAB', 'POLYMED', 'POLYPLEX', 'PONNIERODE', 'POONAWALLA', 'POWERGRID', 'POWERINDIA', 'POWERMECH', 'PPAP', 'PPL', 'PRAENG', 'PRAJIND', 'PRAKASH', 'PRAKASHSTL', 'PRECAM', 'PRECWIRE', 'PREMIERPOL', 'PRESSMN', 'PRESTIGE', 'PRICOLLTD', 'PRIMESECU', 'PRINCEPIPE', 'PRITIKAUTO', 'PRIVISCL', 'PROZONINTU', 'PRSMJOHNSN', 'PSB', 'PSPPROJECT', 'PSUBNKBEES', 'PTC', 'PTL', 'PUNJABCHEM', 'PURVA', 'PVR', 'QGOLDHALF', 'QNIFTY', 'QUESS', 'QUICKHEAL', 'RADICO', 'RADIOCITY', 'RAILTEL', 'RAIN', 'RAJESHEXPO', 'RAJTV', 'RALLIS', 'RAMANEWS', 'RAMASTEEL', 'RAMCOCEM', 'RAMCOIND', 'RAMCOSYS', 'RAMKY', 'RANASUG', 'RANEENGINE', 'RANEHOLDIN', 'RATEGAIN', 'RATNAMANI', 'RAYMOND', 'RBL', 'RBLBANK', 'RCF', 'RCOM', 'RECLTD', 'REDINGTON', 'REFEX', 'RELAXO', 'RELIANCE', 'RELIGARE', 'REMSONSIND', 'RENUKA', 'REPCOHOME', 'REPRO', 'RESPONIND', 'REVATHI', 'RGL', 'RHIM', 'RICOAUTO', 'RIIL', 'RITES', 'RKFORGE', 'RML', 'ROLEXRINGS', 'ROLLT', 'ROSSARI', 'ROSSELLIND', 'ROUTE', 'RPGLIFE', 'RPOWER', 'RPPINFRA', 'RPSGVENT', 'RSSOFTWARE', 'RSWM', 'RTNINDIA', 'RTNPOWER', 'RUBYMILLS', 'RUCHIRA', 'RUPA', 'RUSHIL', 'RVHL', 'RVNL', 'S&SPOWER', 'SADBHAV', 'SADBHIN', 'SAGCEM', 'SAIL', 'SAKHTISUG', 'SAKSOFT', 'SAKUMA', 'SALASAR', 'SALSTEEL', 'SANDESH', 'SANDHAR', 'SANGAMIND', 'SANGHIIND', 'SANGHVIMOV', 'SANOFI', 'SANSERA', 'SAPPHIRE', 'SARDAEN', 'SARLAPOLY', 'SASKEN', 'SASTASUNDR', 'SATIA', 'SATIN', 'SBC', 'SBICARD', 'SBILIFE', 'SBIN', 'SCHAEFFLER', 'SCHAND', 'SCHNEIDER', 'SCI', 'SDBL', 'SECURKLOUD', 'SELAN', 'SEQUENT', 'SESHAPAPER', 'SETCO', 'SETFNIF50', 'SETFNIFBK', 'SEYAIND', 'SFL', 'SGIL', 'SGL', 'SHAKTIPUMP', 'SHALBY', 'SHALPAINTS', 'SHANKARA', 'SHANTIGEAR', 'SHARDACROP', 'SHAREINDIA', 'SHARIABEES', 'SHIL', 'SHILPAMED', 'SHIVALIK', 'SHIVAMILLS', 'SHK', 'SHOPERSTOP', 'SHREDIGCEM', 'SHREECEM', 'SHREEPUSHK', 'SHREERAMA', 'SHREYANIND', 'SHREYAS', 'SHRIRAMCIT', 'SHRIRAMEPC', 'SHRIRAMPPS', 'SHYAMMETL', 'SIEMENS', 'SIGACHI', 'SILINV', 'SIMBHALS', 'SIMPLEXINF', 'SIS', 'SIYSIL', 'SJS', 'SJVN', 'SKFINDIA', 'SKIPPER', 'SKMEGGPROD', 'SMARTLINK', 'SMCGLOBAL', 'SMLISUZU', 'SMLT', 'SMSLIFE', 'SMSPHARMA', 'SNOWMAN', 'SOBHA', 'SOLARA', 'SOLARINDS', 'SOMANYCERA', 'SONACOMS', 'SONATSOFTW', 'SORILINFRA', 'SOTL', 'SOUTHBANK', 'SPAL', 'SPANDANA', 'SPARC', 'SPECIALITY', 'SPIC', 'SPICEJET', 'SPLIL', 'SREEL', 'SRF', 'SRHHYPOLTD', 'SRIPIPES', 'SRTRANSFIN', 'SSWL', 'STAR', 'STARCEMENT', 'STARHEALTH', 'STARPAPER', 'STCINDIA', 'STEELCAS', 'STEELXIND', 'STEL', 'STERTOOLS', 'STLTECH', 'STOVEKRAFT', 'STYLAMIND', 'SUBROS', 'SUDARSCHEM', 'SUMEETINDS', 'SUMICHEM', 'SUMMITSEC', 'SUNCLAYLTD', 'SUNDARMFIN', 'SUNDRMBRAK', 'SUNDRMFAST', 'SUNFLAG', 'SUNPHARMA', 'SUNTECK', 'SUNTV', 'SUPERHOUSE', 'SUPERSPIN', 'SUPPETRO', 'SUPRAJIT', 'SUPREMEIND', 'SUPRIYA', 'SURANAT&P', 'SURYALAXMI', 'SURYAROSNI', 'SURYODAY', 'SUTLEJTEX', 'SUVEN', 'SUVENPHAR', 'SUVIDHAA', 'SUZLON', 'SVPGLOB', 'SWANENERGY', 'SWARAJENG', 'SWELECTES', 'SWSOLAR', 'SYMPHONY', 'SYNGENE', 'TAINWALCHM', 'TAJGVK', 'TAKE', 'TALBROAUTO', 'TANLA', 'TARAPUR', 'TARC', 'TARMAT', 'TARSONS', 'TATACHEM', 'TATACOFFEE', 'TATACOMM', 'TATACONSUM', 'TATAELXSI', 'TATAINVEST', 'TATAMETALI', 'TATAMOTORS', 'TATAMTRDVR', 'TATAPOWER', 'TATASTEEL', 'TATASTLLP', 'TATVA', 'TBZ', 'TCI', 'TCIDEVELOP', 'TCIEXP', 'TCIFINANCE', 'TCNSBRANDS', 'TCPLPACK', 'TCS', 'TDPOWERSYS', 'TEAMLEASE', 'TECHM', 'TECHNOE', 'TEGA', 'TEJASNET', 'TERASOFT', 'TEXINFRA', 'TEXMOPIPES', 'TEXRAIL', 'TFCILTD', 'TGBHOTELS', 'THANGAMAYL', 'THEINVEST', 'THEMISMED', 'THERMAX', 'THOMASCOOK', 'THYROCARE', 'TIDEWATER', 'TIIL', 'TIINDIA', 'TIJARIA', 'TIL', 'TIMESGTY', 'TIMETECHNO', 'TIMKEN', 'TINPLATE', 'TIRUMALCHM', 'TITAN', 'TMRVL', 'TNPETRO', 'TNPL', 'TOKYOPLAST', 'TORNTPHARM', 'TORNTPOWER', 'TREEHOUSE', 'TREJHARA', 'TRENT', 'TRIDENT', 'TRIGYN', 'TRIL', 'TRITURBINE', 'TRIVENI', 'TTKPRESTIG', 'TTL', 'TV18BRDCST', 'TVSELECT', 'TVSMOTOR', 'TVSSRICHAK', 'TVTODAY', 'TWL', 'UBL', 'UCALFUEL', 'UCOBANK', 'UDAICEMENT', 'UFLEX', 'UFO', 'UGARSUGAR', 'UGROCAP', 'UJJIVAN', 'UJJIVANSFB', 'ULTRACEMCO', 'UNICHEMLAB', 'UNIDT', 'UNIONBANK', 'UNIVCABLES', 'UNIVPHOTO', 'UPL', 'USHAMART', 'UTIAMC', 'UTIBANKETF', 'UTINEXT50', 'UTINIFTETF', 'UTISENSETF', 'UTISXN50', 'UTTAMSTL', 'UTTAMSUGAR', 'VADILALIND', 'VAIBHAVGBL', 'VAKRANGEE', 'VALIANTORG', 'VARROC', 'VASCONEQ', 'VASWANI', 'VBL', 'VEDL', 'VENUSREM', 'VESUVIUS', 'VETO', 'VGUARD', 'VHL', 'VIDHIING', 'VIJAYA', 'VIKASLIFE', 'VIKASPROP', 'VIKASWSP', 'VIMTALABS', 'VINATIORGA', 'VINDHYATEL', 'VINEETLAB', 'VINYLINDIA', 'VIPCLOTHNG', 'VIPIND', 'VISAKAIND', 'VISHAL', 'VISHWARAJ', 'VIVIMEDLAB', 'VLSFINANCE', 'VMART', 'VOLTAMP', 'VOLTAS', 'VRLLOG', 'VSSL', 'VSTIND', 'VSTTILLERS', 'VTL', 'WABAG', 'WABCOINDIA', 'WALCHANNAG', 'WATERBASE', 'WEBELSOLAR', 'WEIZMANIND', 'WELCORP', 'WELENT', 'WELINV', 'WELSPUNIND', 'WENDT', 'WESTLIFE', 'WHEELS', 'WHIRLPOOL', 'WINDLAS', 'WINDMACHIN', 'WINPRO', 'WIPRO', 'WOCKPHARMA', 'WONDERLA', 'WORTH', 'WSTCSTPAPR', 'XCHANGING', 'XELPMOC', 'YAARI', 'YESBANK', 'YUKEN', 'ZEEL', 'ZEELEARN', 'ZENITHEXPO', 'ZENSARTECH', 'ZENTEC', 'ZODIAC', 'ZODIACLOTH', 'ZOMATO', 'ZUARI', 'ZUARIGLOB', 'ZYDUSWELL']
both_in_nse_bse_excluding_n500	watchlist = ['20MICRONS','21STCENMGM','3PLAND','5PAISA','63MOONS','AARTISURF','AARVEEDEN','ABSLAMC','ABSLBANETF','ABSLNN50ET','ACCELYA','ACE','ACRYSIL','ADANIPOWER','ADFFOODS','ADORWELD','ADSL','ADVANIHOTR','AGARIND','AHLEAST','AHLUCONT','AJMERA','AJRINFRA','AKSHOPTFBR','ALANKIT','ALICON','ALKALI','ALLCARGO','ALLSEC','ALMONDZ','ALPA','ALPHAGEO','AMBICAAGAR','AMBIKCO','AMDIND','AMIORG','AMJLAND','AMRUTANJAN','ANANDRATHI','ANANTRAJ','ANDHRACEMT','ANDHRAPAP','ANDHRSUGAR','ANDREWYU','ANGELONE','ANIKINDS','ANMOL','ANUP','ANURAS','APARINDS','APCL','APCOTEXIND','APEX','APOLLO','APTECHT','APTUS','ARCHIDPLY','ARCHIES','ARENTERP','ARIES','ARMANFIN','AROGRANITE','ARROWGREEN','ARSHIYA','ARSSINFRA','ARTEMISMED','ARVIND','ARVINDFASN','ASAHISONG','ASALCBR','ASHAPURMIN','ASHIANA','ASHIMASYN','ASIANENE','ASIANHOTNR','ASIANTILES','ASTEC','ASTRAMICRO','ASTRON','ATFL','ATULAUTO','AURIONPRO','AURUM','AUSOMENT','AUTOAXLES','AUTOIND','AVADHSUGAR','AVTNPL','AWHCL','AXISCADES','AXISCETF','AXISGOLD','AXISTECETF','AYMSYNTEX','BAJAJHCARE','BAJAJHIND','BALAJITELE','BALKRISHNA','BALPHARMA','BANARBEADS','BANARISUG','BANCOINDIA','BANG','BANKBEES','BANSWRAS','BARBEQUE','BASML','BBETF0432','BBL','BBOX','BCP','BEARDSELL','BECTORFOOD','BEDMUTHA','BEPL','BESTAGRO','BFINVEST','BFUTILITIE','BGRENERGY','BHAGCHEM','BHAGYAPROP','BHARATGEAR','BHARATWIRE','BIGBLOC','BIL','BINDALAGRO','BIOFILCHEM','BIRLACABLE','BIRLAMONEY','BLBLIMITED','BLKASHYAP','BODALCHEM','BOMDYEING','BOROLTD','BORORENEW','BRNL','BROOKS','BSL','BSLGOLDETF','BSLSENETFG','BURNPUR','CAMLINFINE','CAPACITE','CAREERP','CARERATING','CARTRADE','CCHHL','CEBBCO','CELEBRITY','CENTENKA','CENTEXT','CENTRUM','CENTUM','CEREBRAINT','CHEMBOND','CHEMCON','CHEMPLASTS','CHENNPETRO','CINELINE','CLEAN','CLNINDIA','COASTCORP','COFFEEDAY','COMPUSOFT','CONFIPET','CONTROLPR','CORALFINAC','CORDSCABLE','COSMOFILMS','COUNCODOS','CPSEETF','CRAFTSMAN','CTE','CUBEXTUB','CUPID','CYBERMEDIA','CYBERTECH','DAAWAT','DALMIASUG','DATAMATICS','DATAPATTNS','DBCORP','DBSTOCKBRO','DCMNVL','DECCANCE','DEEPAKFERT','DEEPENR','DELPHIFX','DELTAMAGNT','DEN','DEVYANI','DHAMPURSUG','DHANBANK','DHARAMSI','DHARSUGAR','DHRUV','DHUNINV','DIAMONDYD','DICIND','DIGISPICE','DLINKINDIA','DODLA','DOLATALGO','DOLLAR','DREDGECORP','DSPNEWETF','DSSL','DVL','DWARKESH','DYNPRO','EASTSILK','EBBETF0423','EBBETF0425','EBBETF0430','EBBETF0431','EIHAHOTELS','EIMCOELECO','EKC','ELECON','ELECTCAST','ELECTHERM','EMAMIPAP','EMAMIREAL','EMKAY','EMMBI','ENERGYDEV','ENIL','EQUIPPP','EQUITASBNK','EROSMEDIA','ESABINDIA','ESSARSHPNG','ESTER','EVEREADY','EVERESTIND','EXCELINDUS','EXPLEOSOL','EXXARO','FACT','FAIRCHEMOR','FCL','FEL','FELDVR','FIEMIND','FILATEX','FINOPB','FLEXITUFF','FLFL','FMGOETZE','FMNL','FOCUS','FOODSIN','FORCEMOT','FOSECOIND','FSC','GABRIEL','GAL','GALLANTT','GALLISPAT','GANDHITUBE','GANECOS','GANESHBE','GANESHHOUC','GATI','GAYAPROJ','GDL','GEECEE','GENCON','GENESYS','GENUSPAPER','GENUSPOWER','GEOJITFSL','GET&D','GFLLIMITED','GHCL','GICHSGFIN','GILLANDERS','GINNIFILA','GIPCL','GLAND','GLOBALVECT','GLOBUSSPR','GLS','GMBREW','GMDCLTD','GNA','GOACARBON','GOCLCORP','GOCOLORS','GOKEX','GOKUL','GOKULAGRO','GOLDBEES','GOLDIAM','GOLDSHARE','GOODLUCK','GOODYEAR','GPIL','GPTINFRA','GRAUWEIL','GRAVITA','GREENPANEL','GREENPLY','GRINFRA','GRPLTD','GSCLCEMENT','GTL','GTNTEX','GTPL','GUFICBIO','GUJAPOLLO','GULFPETRO','HARRMALAYA','HATHWAY','HBANKETF','HBLPOWER','HCC','HCG','HCL-INSYS','HDFCMFGETF','HDFCNIFETF','HERANBA','HERCULES','HERITGFOOD','HESTERBIO','HEXATRADEX','HGINFRA','HGS','HIKAL','HIL','HIMATSEIDE','HINDCOMPOS','HINDNATGLS','HINDOILEXP','HIRECT','HITECH','HITECHCORP','HITECHGEAR','HLEGLAS','HMVL','HNDFDS','HNGSNGBEES','HOMEFIRST','HONDAPOWER','HOVS','HPL','HSIL','HTMEDIA','HUBTOWN','ICICI500','ICICIALPLV','ICICIB22','ICICIBANKN','ICICIBANKP','ICICICONSU','ICICIFMCG','ICICIGOLD','ICICILIQ','ICICILOVOL','ICICIM150','ICICIMCAP','ICICINF100','ICICINIFTY','ICICINV20','ICICINXT50','ICICIPHARM','ICICISENSX','ICICITECH','ICRA','IDBIGOLD','IFBAGRO','IFCI','IFGLEXPOR','IGARASHI','IGPL','IIFLSEC','IMFA','IMPAL','INCREDIBLE','INDBANK','INDIAGLYCO','INDIANCARD','INDIANHUME','INDIGOPNTS','INDLMETER','INDNIPPON','INDORAMA','INDOSTAR','INDOTECH','INDOTHAI','INDRAMEDCO','INDSWFTLAB','INDSWFTLTD','INDTERRAIN','INEOSSTYRO','INFRABEES','INOXWIND','INSECTICID','INTENTECH','INTLCONV','INVENTURE','IPL','IRFC','IRIS','ISFT','ISGEC','ISMTLTD','ITDC','ITDCEM','IVC','IVP','IVZINGOLD','IZMO','J&KBANK','JAGRAN','JAGSNPHARM','JAIBALAJI','JAICORPLTD','JAYAGROGN','JAYBARMARU','JBMA','JETFREIGHT','JHS','JINDALPHOT','JINDALPOLY','JINDRILL','JINDWORLD','JISLJALEQS','JKIL','JMCPROJECT','JPASSOCIAT','JPINFRATEC','JPPOWER','JSWHL','JSWISPL','JTLINFRA','JUBLINDS','JUBLINGREA','JUBLPHARMA','JUNIORBEES','KABRAEXTRU','KAKATCEM','KALYANKJIL','KAMATHOTEL','KAMDHENU','KANANIIND','KANORICHEM','KANPRPLA','KARMAENG','KAUSHALYA','KAYA','KBCGLOBAL','KCP','KCPSUGIND','KDDL','KELLTONTEC','KENNAMET','KESORAMIND','KHADIM','KHAICHEM','KHANDSE','KICL','KILITCH','KIMS','KINGFA','KIOCL','KIRIINDUS','KIRLFER','KIRLOSBROS','KIRLOSENG','KIRLOSIND','KITEX','KKCL','KMSUGAR','KOKUYOCMLN','KOLTEPATIL','KOPRAN','KOTAKBKETF','KOTAKGOLD','KOTAKNIFTY','KOTAKPSUBK','KOTHARIPRO','KOVAI','KPIGLOBAL','KREBSBIO','KRSNAA','KSL','KTKBANK','KUANTUM','LAMBODHARA','LASA','LATENTVIEW','LCCINFOTEC','LGBBROSLTD','LGBFORGE','LIBERTSHOE','LICNETFN50','LICNETFSEN','LICNFNHGP','LIKHITHA','LINC','LIQUIDBEES','LIQUIDETF','LODHA','LOKESHMACH','LPDC','LUMAXIND','LUMAXTECH','LXCHEM','LYKALABS','LYPSAGEMS','MAANALU','MADHAV','MADRASFERT','MAESGETF','MAFANG','MAFSETF','MAGNUM','MAHASTEEL','MAHEPC','MAHKTECH','MAHLIFE','MAITHANALL','MALUPAPER','MAN50ETF','MANAKSIA','MANALIPETC','MANGALAM','MANGCHEFER','MANGLMCEM','MANGTIMBER','MANINDS','MANINFRA','MANORG','MAPMYINDIA','MARALOVER','MARATHON','MARKSANS','MASPTOP50','MASTEK','MATRIMONY','MAWANASUG','MAXVIL','MAYURUNIQ','MBLINFRA','MCLEODRUSS','MEDICAMEQ','MEDPLUS','MENONBE','METROBRAND','MFL','MINDTECK','MIRCELECTR','MIRZAINT','MMFL','MODISNME','MOGSEC','MOHITIND','MOL','MOLDTKPAC','MOM100','MOM50','MON100','MONTECARLO','MORARJEE','MOREPENLAB','MPSLTD','MRO-TEK','MSPL','MTARTECH','MTEDUCARE','MTNL','MUKANDLTD','MUKTAARTS','MUNJALAU','MUNJALSHOW','MURUDCERA','NACLIND','NAGREEKCAP','NAGREEKEXP','NAHARCAP','NAHARINDUS','NAHARPOLY','NATHBIOGEN','NAVKARCORP','NAVNETEDUL','NBVENTURES','NCLIND','NDL','NDRAUTO','NDTV','NECCLTD','NECLIFE','NELCAST','NEOGEN','NETFNIF100','NEULANDLAB','NEWGEN','NIBL','NIFTYBEES','NIITLTD','NIPPOBATRY','NIRAJ','NITCO','NKIND','NOIDATOLL','NOVARTIND','NRBBEARING','NSIL','NUCLEUS','NURECA','NUVOCO','NXTDIGITAL','NYKAA','OAL','OMAXAUTO','OMAXE','OMINFRAL','ONELIFECAP','ONMOBILE','ONWARDTEC','OPTIEMUS','ORBTEXP','ORIENTABRA','ORIENTALTL','ORIENTBELL','ORIENTCEM','ORIENTHOT','ORIENTLTD','ORIENTPPR','ORISSAMINE','OSWALAGRO','PAISALO','PANACEABIO','PANACHE','PANAMAPET','PARAGMILK','PARAS','PARSVNATH','PASUPTAC','PATELENG','PATINTLOG','PATSPINLTD','PAYTM','PBAINFRA','PCJEWELLER','PDMJEPAPER','PDSMFL','PEARLPOLY','PENIND','PFOCUS','PFS','PGEL','PGIL','PILANIINVS','PILITA','PIONDIST','PIONEEREMB','PITTIENG','PLASTIBLEN','PNBGILTS','PNC','POKARNA','POLICYBZR','PONNIERODE','POONAWALLA','POWERMECH','PPAP','PPL','PRAENG','PRAJIND','PRAKASH','PRAKASHSTL','PRECAM','PRECWIRE','PREMIERPOL','PRESSMN','PRICOLLTD','PRIMESECU','PRITIKAUTO','PRIVISCL','PROZONINTU','PSB','PSPPROJECT','PSUBNKBEES','PTC','PTL','PUNJABCHEM','PURVA','QGOLDHALF','QNIFTY','QUICKHEAL','RADIOCITY','RAILTEL','RAJTV','RAMANEWS','RAMASTEEL','RAMCOIND','RAMCOSYS','RAMKY','RANASUG','RANEENGINE','RANEHOLDIN','RATEGAIN','RBL','RCOM','REFEX','RELIGARE','REMSONSIND','RENUKA','REPCOHOME','REPRO','REVATHI','RGL','RHIM','RICOAUTO','RIIL','RKFORGE','RML','ROLEXRINGS','ROLLT','ROSSELLIND','RPGLIFE','RPOWER','RPPINFRA','RPSGVENT','RSSOFTWARE','RSWM','RTNINDIA','RTNPOWER','RUBYMILLS','RUCHIRA','RUPA','RUSHIL','RVHL','S&SPOWER','SADBHAV','SADBHIN','SAGCEM','SAKHTISUG','SAKSOFT','SAKUMA','SALASAR','SALSTEEL','SANDESH','SANDHAR','SANGAMIND','SANGHIIND','SANGHVIMOV','SANSERA','SAPPHIRE','SARDAEN','SARLAPOLY','SASKEN','SASTASUNDR','SATIA','SATIN','SBC','SCHAND','SDBL','SECURKLOUD','SELAN','SESHAPAPER','SETCO','SETFNIF50','SETFNIFBK','SEYAIND','SGIL','SGL','SHAKTIPUMP','SHALBY','SHALPAINTS','SHANKARA','SHANTIGEAR','SHAREINDIA','SHARIABEES','SHIL','SHIVALIK','SHIVAMILLS','SHK','SHREDIGCEM','SHREEPUSHK','SHREERAMA','SHREYANIND','SHREYAS','SHRIRAMEPC','SHRIRAMPPS','SHYAMMETL','SIGACHI','SILINV','SIMBHALS','SIMPLEXINF','SIYSIL','SJS','SKIPPER','SKMEGGPROD','SMARTLINK','SMCGLOBAL','SMLISUZU','SMLT','SMSLIFE','SMSPHARMA','SNOWMAN','SOMANYCERA','SONACOMS','SORILINFRA','SOTL','SOUTHBANK','SPAL','SPECIALITY','SPIC','SPLIL','SREEL','SRHHYPOLTD','SRIPIPES','SSWL','STARHEALTH','STARPAPER','STCINDIA','STEELCAS','STEELXIND','STEL','STERTOOLS','STOVEKRAFT','STYLAMIND','SUBROS','SUMEETINDS','SUMMITSEC','SUNDRMBRAK','SUNFLAG','SUPERHOUSE','SUPERSPIN','SUPRIYA','SURANAT&P','SURYALAXMI','SURYAROSNI','SURYODAY','SUTLEJTEX','SUVEN','SUVIDHAA','SVPGLOB','SWARAJENG','SWELECTES','TAINWALCHM','TAJGVK','TAKE','TALBROAUTO','TARAPUR','TARC','TARMAT','TARSONS','TATAMETALI','TATASTLLP','TATVA','TBZ','TCI','TCIDEVELOP','TCIFINANCE','TCPLPACK','TDPOWERSYS','TECHNOE','TEGA','TEJASNET','TERASOFT','TEXINFRA','TEXMOPIPES','TEXRAIL','TFCILTD','TGBHOTELS','THANGAMAYL','THEINVEST','THEMISMED','THOMASCOOK','TIDEWATER','TIIL','TIJARIA','TIL','TIMESGTY','TIMETECHNO','TINPLATE','TIRUMALCHM','TMRVL','TNPETRO','TNPL','TOKYOPLAST','TREEHOUSE','TREJHARA','TRIGYN','TRIL','TRIVENI','TTL','TVSELECT','TVSSRICHAK','TVTODAY','TWL','UCALFUEL','UDAICEMENT','UFO','UGARSUGAR','UGROCAP','UNICHEMLAB','UNIDT','UNIVCABLES','UNIVPHOTO','USHAMART','UTIBANKETF','UTINEXT50','UTINIFTETF','UTISENSETF','UTISXN50','UTTAMSTL','UTTAMSUGAR','VADILALIND','VASCONEQ','VASWANI','VENUSREM','VESUVIUS','VETO','VHL','VIDHIING','VIJAYA','VIKASLIFE','VIKASPROP','VIKASWSP','VIMTALABS','VINDHYATEL','VINEETLAB','VINYLINDIA','VIPCLOTHNG','VISAKAIND','VISHAL','VISHWARAJ','VIVIMEDLAB','VLSFINANCE','VOLTAMP','VRLLOG','VSSL','VSTTILLERS','WABAG','WALCHANNAG','WATERBASE','WEBELSOLAR','WEIZMANIND','WELENT','WELINV','WENDT','WHEELS','WINDLAS','WINDMACHIN','WINPRO','WONDERLA','WORTH','WSTCSTPAPR','XCHANGING','XELPMOC','YAARI','YUKEN','ZEELEARN','ZENITHEXPO','ZENTEC','ZODIAC','ZODIACLOTH','ZOMATO','ZUARI','ZUARIGLOB']

29.

try:
	df = retrive_orderbook()
	print(df[['order_id', 'tradingsymbol', 'status', 'status_message', 'exchange_update_timestamp']])

	status_buy_orderid = df.loc[buy_orderid].iloc[-1]['status']
	status_sell_orderid = df.loc[sell_orderid].iloc[-1]['status']

except Exception as e:
	print(e)
	pdb.set_trace()


30. make coumputer speak
	import winsound
	frequency = 2500  # Set Frequency To 2500 Hertz
	duration = 1000  # Set Duration To 1000 ms == 1 second
	winsound.Beep(frequency, duration)


31. compare speed
	import time
	st = time.time()

	for x in range(1,10000):
		abc = x

	end = time.time()
	print(f"called tick data it took  {end - st} sec")

32.
    completed_candle = pd.Series(datetime.datetime.now()).dt.floor('15min')[0] - datetime.timedelta(minutes=15)
    completed_candle = completed_candle.strftime("%Y-%m-%d %H:%M:%S+05:30")

33. 
	https://stackoverflow.com/questions/20457038/how-to-round-to-2-decimals-with-python


34. ltp and token
	ltp = kite.ltp(['NSE:' + name])['NSE:' + name]['last_price']
	token = kite.ltp(['NSE:' + name])['NSE:' + name]['instrument_token']


35. make index 1,2,3,4,5
	df.reset_index(drop=True)

36. common status
	status = {'name':None, 'date':None ,'entry_time': None, 'entry_price': None, 'buy_sell': None, 'qty': None, 'sl': None, 'exit_time': None, 'exit_price': None, 'pnl': None, 'remark': None, 'tarded':None}


37. base files
	pass

38. pandas put multiple conditions
	df5['first_entry'] = (df5['rsi'] > bull_level) | (df5['rsi'] < bear_level)

39. pandas find location of first occurrence
	df.loc[df['rsi'] > rsi_bull_level]['date'][0]

40. condended if else
	i = 5 if a > 7 else 0
	x = a if cond else b

41. pandas rename columns
	df.rename({"A": "new_a", "B": "new_b"}, axis='columns', inplace =True)


42. get latest order history
	order_history = pd.DataFrame(kite.order_history(order_id = status[name]['parent_order'])).iloc[-1]


43. get inst book
	inst = pd.DataFrame(kite.instruments())
	inst = inst.set_index(inst['tradingsymbol'])



44. select rows if row data is in a list
	nse_file = nse_file[nse_file['Symbol'].isin(nifty50)]

45. update a cell value
	df.at[row_no,'column_name'] = 400

46. pandas normalise values
	df["normal_close"] = df["close"] / df["close"].max()


47. get canlde volume color in dataframe .. matched to zerodha volume candle color
	df['previous_close'] = df['close'].shift(1)
	df['volume_color'] = np.where(df['close'] > df['previous_close'], 'green_volume', 'volume_red')



48. pandas convert string to datetime
	df['date'] = pd.to_datetime(df['date'])


49. weekly resampling
	
	logic = {'open'  : 'first', 'high'  : 'max', 'low'   : 'min', 'close' : 'last', 'volume': 'sum'}
	df.resample('W-MON', closed= "left", label="left").apply(logic)



50. monthly resampling
	logic = {'open': 'first', 'high': 'max', 'low': 'min', 'close': 'last', 'volume': 'sum'}
    mdf = df.resample('MS').apply(logic)


51 . Intrday pnl

	pnl = pd.DataFrame(kite.positions()['day'])['pnl'].sum()


52 . positional pnl for fno

	pnl = pd.DataFrame(kite.positions()['net'])['pnl'].sum()


53. get freeze quantity

	import pandas as pd
	df = pd.read_excel(r'https://archives.nseindia.com/content/fo/qtyfreeze.xls')
	print(df)

54 . Temp lot sizes
	lot_size_temp = {'AARTIIND' : 850, 'ACC' : 250, 'ADANIENT' : 500, 'ADANIPORTS' : 1250, 'ALKEM' : 200, 'AMARAJABAT' : 1000, 'AMBUJACEM' : 1500, 'APLLTD' : 700, 'APOLLOHOSP' : 125, 'APOLLOTYRE' : 2500, 'ASHOKLEY' : 4500, 'ASIANPAINT' : 150, 'AUBANK' : 500, 'AUROPHARMA' : 750, 'AXISBANK' : 1200, 'BAJAJ-AUTO' : 250, 'BAJAJFINSV' : 50, 'BAJFINANCE' : 125, 'BALKRISIND' : 200, 'BANDHANBNK' : 1800, 'BANKBARODA' : 11700, 'BATAINDIA' : 550, 'BEL' : 3800, 'BERGEPAINT' : 1100, 'BHARATFORG' : 750, 'BHARTIARTL' : 950, 'BHEL' : 10500, 'BIOCON' : 2300, 'BOSCHLTD' : 50, 'BPCL' : 1800, 'BRITANNIA' : 200, 'CADILAHC' : 1100, 'CANBK' : 5400, 'CHOLAFIN' : 1250, 'CIPLA' : 650, 'COALINDIA' : 4200, 'COFORGE' : 100, 'COLPAL' : 350, 'CONCOR' : 800, 'CUB' : 3400, 'CUMMINSIND' : 600, 'DABUR' : 1250, 'DEEPAKNTR' : 250, 'DIVISLAB' : 100, 'DLF' : 1650, 'DRREDDY' : 125, 'EICHERMOT' : 350, 'ESCORTS' : 550, 'EXIDEIND' : 3600, 'FEDERALBNK' : 10000, 'GAIL' : 6100, 'GLENMARK' : 1150, 'GMRINFRA' : 22500, 'GODREJCP' : 500, 'GODREJPROP' : 325, 'GRANULES' : 1550, 'GRASIM' : 475, 'GUJGASLTD' : 1250, 'HAVELLS' : 500, 'HCLTECH' : 700, 'HDFC' : 300, 'HDFCAMC' : 200, 'HDFCBANK' : 550, 'HDFCLIFE' : 1100, 'HEROMOTOCO' : 300, 'HINDALCO' : 1075, 'HINDPETRO' : 2700, 'HINDUNILVR' : 300, 'IBULHSGFIN' : 3100, 'ICICIBANK' : 1375, 'ICICIGI' : 425, 'ICICIPRULI' : 750, 'IDEA' : 70000, 'IDFCFIRSTB' : 11100, 'IGL' : 1375, 'INDIGO' : 250, 'INDUSINDBK' : 900, 'INDUSTOWER' : 2800, 'INFY' : 300, 'IOC' : 6500, 'IRCTC' : 875, 'ITC' : 3200, 'JINDALSTEL' : 2500, 'JSWSTEEL' : 1350, 'JUBLFOOD' : 125, 'KOTAKBANK' : 400, 'L&TFH' : 8924, 'LALPATHLAB' : 125, 'LICHSGFIN' : 2000, 'LT' : 575, 'LTI' : 150, 'LTTS' : 200, 'LUPIN' : 850, 'M&M' : 700, 'M&MFIN' : 4000, 'MANAPPURAM' : 3000, 'MARICO' : 1000, 'MARUTI' : 100, 'MCDOWELL-N' : 1250, 'MFSL' : 650, 'MGL' : 600, 'MINDTREE' : 200, 'MOTHERSUMI' : 3500, 'MPHASIS' : 175, 'MRF' : 10, 'MUTHOOTFIN' : 375, 'NAM-INDIA' : 1600, 'NATIONALUM' : 8500, 'NAUKRI' : 125, 'NAVINFLUOR' : 225, 'NESTLEIND' : 25, 'NMDC' : 6700, 'NTPC' : 5700, 'ONGC' : 7700, 'PAGEIND' : 30, 'PEL' : 275, 'PETRONET' : 3000, 'PFC' : 6200, 'PFIZER' : 125, 'PIDILITIND' : 250, 'PIIND' : 250, 'PNB' : 16000, 'POWERGRID' : 5333, 'PVR' : 407, 'RAMCOCEM' : 850, 'RBLBANK' : 2900, 'RECLTD' : 6000, 'RELIANCE' : 250, 'SAIL' : 4750, 'SBILIFE' : 750, 'SBIN' : 1500, 'SHREECEM' : 25, 'SIEMENS' : 275, 'SRF' : 375, 'SRTRANSFIN' : 400, 'SUNPHARMA' : 700, 'SUNTV' : 1500, 'TATACHEM' : 1000, 'TATACONSUM' : 675, 'TATAMOTORS' : 2850, 'TATAPOWER' : 6750, 'TATASTEEL' : 425, 'TCS' : 150, 'TECHM' : 600, 'TITAN' : 375, 'TORNTPHARM' : 250, 'TORNTPOWER' : 1500, 'TRENT' : 725, 'TVSMOTOR' : 1400, 'UBL' : 350, 'ULTRACEMCO' : 100, 'UPL' : 1300, 'VEDL' : 3100, 'VOLTAS' : 500, 'WIPRO' : 800, 'ZEEL' : 3000}